username:
password:
phone_number:

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- software engineer
#- full stack developer
#- product developer

locations:
- remote



salary: 19
rate: 800
# --------- Optional Parameters -------
uploads:
  Resume: 'C:\Users\badhe\Downloads\Anil_Resume_.pdf'
  #Photo: # PATH TO photo


output_filename:
- C:\Users\badhe\Desktop\Easy\LinkedIn-Easy-Apply-Bot\output.csv

blacklist:
 - EPAM
 - Tata Consultancy Services